on:
  workflow_dispatch:
jobs:
  Phigros:
    runs-on: ubuntu-22.04
    steps:
    - run: git clone https://github.com/7aGiven/workflow .
    - run: dpkg -L libogg0
    - run: dpkg -L libvorbis0a
    - run: ls -lh /usr/lib/x86_64-linux-gnu/
    - run: ls -lh .
    - run: python3 a.py
    - run: ls -lh .
