on:
  workflow_dispatch:
jobs:
  Phigros:
    runs-on: ubuntu-22.04
    steps:
    - run: git clone https://github.com/7aGiven/workflow .
    - run: dpkg -L libogg0
    - run: dpkg -L libvorbis0a
    - run: apt list libvorbisenc2
    - run: sudo apt-get install libvorbisenc2
    - run: ls -lh .
    - run: pip install fsb5
    - run: python3 a.py
    - run: ls -lh .
